const $=id=>document.getElementById(id);
const TOTAL_WEEKS=12;
const fixedActs=['THE STATIC KITTENS','VELVET KNIFE','ELECTRIC MOTHER','THE DENTISTS','FUNERAL DISCO','THE BAD DECISIONS','CARPET BURNS','SISTER PANIC','DEAD RADIO','CHEAP PERFUME','HORSE PROBLEM','THE TAX EXILES','MILD PERIL','TINY KNIVES','TELEPHONE JESUS','THE TUESDAY PEOPLE','THE PLASTIC SAINTS','UNCLE DAMAGE','THE WRONG TROUSERS','FREE BISCUIT','MOTORWAY SERVICES','BAD HAIRCUT','THE REGULARS','SUNDAY’S PROBLEM','MILK CRISIS','PAPER TIGER','THE SPARE KEYS','HOTEL SOAP','PUBLIC NUISANCE','THE SMALL PRINT','WET CEMENT','NO FIXED ADDRESS','THE LAST ORDERS','DEREK','OTHER DAVE','KEVIN','THE OTHER KEVIN','BUS REPLACEMENT SERVICE','LOCAL SUPPORT','TBC','VERY SPECIAL GUESTS','SAD MACHINE','THE RENTAL CARS','PANIC STATIONS','COLD DINNER','THE DIVORCEES','PLASTIC HORSE','THE AWKWARD SILENCE','DUSTY CARPET','SLOW LEARNERS','GARY & THE RECEIPTS','TWO DRINK MINIMUM','THE APOLOGIES','NORMAL PEOPLE','PARKING FINE','BAD PENNY','THE OVERDRAFTS','THE UNINVITED','SOGGY BISCUIT','EMERGENCY CONTACT','HALF A SANDWICH','THE COMPLAINTS','NOISE VIOLATION','THE LAST BUS','THE FORMER TENANTS','LATE CHECKOUT','THE WRONG NUMBER','BORROWED AMP','THE EXES','TUESDAY NIGHT','THE TEMPORARY BASSISTS','MOTEL BREAKFAST','THE LOST COATS','MINOR DAMAGE','SUSPICIOUS PACKAGE','THE PLUS ONES','UNPAID TAB','THE NICE SHIRTS','LOUD NEIGHBOURS','THE BAD HAIRCUTS','RETURN TO SENDER','SOMEONE’S COUSIN','THE FIRE EXITS','THREE DAY WEEKEND','THE MISPRINTS','LOST PROPERTY','NO COVER CHARGE','THE HOUSE PLANTS','CAR TROUBLE','FREE PARKING','THE SPILL','NOT GARY','THE BACK STAIRS','SOUND CHECK','THE RECEIPTS','WRONG VENUE','THE STANDBYS','MISSING CABLE','LAST MINUTE','THE INCIDENT','CHEAP SEATS','THE WAITING LIST','DOOR STAFF','THE REFUNDS','RAIN DELAY','THE EARLY BIRDS','NO REENTRY','STAGE LEFT','THE WRISTBANDS','MERCH TABLE','THE PORTALOOS','CLOSING TIME'];
const opportunities=[
{id:'kittens',title:'OPEN FOR STATIC KITTENS',meta:'1 WEEK · NO PAY · BIG CROWD',copy:'Their opener vanished. Their audience is exactly the audience you need.',cost:0,weeks:1,base:6,risk:5,relation:'static',problem:['LOU HATES THEIR GUITARIST.','He called Lou’s amp “cute.” Soundcheck has stopped.','MAKE LOU PLAY','LET LOU PROVE A POINT']},
{id:'single',title:'RECORD A SINGLE',meta:'2 WEEKS · £40 · HIGH UPSIDE',copy:'A tiny studio has two free days and a producer who claims to know John Peel.',cost:40,weeks:2,base:8,risk:4,problem:['MICK WROTE A NEW CHORUS.','You have paid for six hours. Mick has used five explaining it.','RECORD MICK’S CHORUS','USE THE OLD ONE']},
{id:'club',title:'PLAY THE KING’S HEAD',meta:'1 WEEK · +£25 · SMALL CROWD',copy:'Nobody important will be there. Probably. You do need the money.',cost:-25,weeks:1,base:2,risk:1,problem:['THE PA HAS ONE WORKING SPEAKER.','The landlord says this is “the good one.”','PLAY ANYWAY','BORROW AN AMP']},
{id:'radio',title:'TAKE A RADIO SESSION',meta:'1 WEEK · £10 · LIVE ON AIR',copy:'Three songs. No second takes. Jane says this is what real bands do.',cost:10,weeks:1,base:7,risk:6,problem:['JANE CHANGED THE KEY.','She tells everyone this thirty seconds before the red light comes on.','FOLLOW JANE','PLAY THE OLD KEY']},
{id:'dentists',title:'SUPPORT THE DENTISTS',meta:'1 WEEK · +£15 · HUMILIATING',copy:'They are above you on the bill. They are also sold out.',cost:-15,weeks:1,base:5,risk:3,relation:'dentists',problem:['THE DENTISTS START EXACTLY ON TIME.','Your soundcheck is still happening. Of course theirs is not.','CUT SOUNDCHECK SHORT','MAKE THEM WAIT']},
{id:'velvet',title:'SHARE A BILL WITH VELVET KNIFE',meta:'1 WEEK · £5 · VERY BAD IDEA',copy:'Great venue. Great crowd. Velvet Knife have already started drinking.',cost:5,weeks:1,base:8,risk:8,relation:'velvet',problem:['MICK HAS DISAPPEARED.','Someone saw him go upstairs with Velvet Knife twenty minutes ago.','GO FIND MICK','START WITHOUT HIM']},
{id:'press',title:'DO THE MUSIC PAPER INTERVIEW',meta:'1 WEEK · FREE · PUBLICITY',copy:'They want a photograph and “some friction.” You have plenty.',cost:0,weeks:1,base:5,risk:5,problem:['THE WRITER ASKS WHO RUNS THE BAND.','Jane and Lou answer at exactly the same time.','SAY JANE','SAY NOBODY']},
{id:'tour',title:'TAKE THE THREE-DATE TOUR',meta:'2 WEEKS · £30 · THREE CITIES',copy:'A borrowed van. Three support slots. One motorway service station per meal.',cost:30,weeks:2,base:10,risk:7,problem:['THE VAN DIES OUTSIDE LEEDS.','Gary used to own the reliable van. Gary is no longer in the band.','PAY £20 FOR A TOW','CALL THE DENTISTS']},
{id:'rehearse',title:'LOCK THE BAND IN REHEARSAL',meta:'1 WEEK · £10 · BORING BUT USEFUL',copy:'No parties. No interviews. No one is allowed to buy a smoke machine.',cost:10,weeks:1,base:1,risk:-5,problem:['LOU WANTS AN ELEVEN-MINUTE SOLO.','The song is three minutes long.','LET HIM TRY IT','ABSOLUTELY NOT']}
];
let state;
function newState(name){return{name:(name||'SUPERMODEL').toUpperCase(),week:1,cash:120,chaos:12,rank:55+Math.floor(Math.random()*31),relations:{static:0,dentists:0,velvet:0},offerIds:[]}}
function save(){localStorage.setItem('headlinerSaveV2',JSON.stringify(state))}
function clamp(){state.cash=Math.max(0,state.cash);state.chaos=Math.max(0,Math.min(100,state.chaos));state.rank=Math.max(1,Math.min(100,state.rank))}
function renderStats(){$('band-title').textContent=state.name;$('rank').textContent=state.rank;$('turn').textContent=Math.min(state.week,TOTAL_WEEKS);$('cash').textContent=state.cash;$('chaos').textContent=state.chaos}
function tierFor(i){if(i<2)return'tier1';if(i<7)return'tier2';if(i<18)return'tier3';if(i<42)return'tier4';return'tier5'}
function tierName(rank){if(rank<=2)return'HEADLINE TYPE';if(rank<=7)return'HUGE TYPE';if(rank<=18)return'BIG TYPE';if(rank<=42)return'MEDIUM TYPE';return'TINY TYPE'}
function billActs(){const a=fixedActs.slice(0,99);a.splice(Math.max(0,Math.min(99,state.rank-1)),0,state.name);return a.slice(0,100)}
function showPoster(message=''){renderStats();if(state.rank===1)return showEnd(true,'YOU ARE THE HEADLINER.','Top of the poster. Somehow.');if(state.week>TOTAL_WEEKS)return showEnd(false,state.rank<=10?'YOU MADE THE BIG PRINT.':'MEGA FESTIVAL IS HERE.',state.rank<=10?'Not the headliner. But nobody needs binoculars to find you.':`You finished at #${state.rank}. The Static Kittens are still annoyingly enormous.`);const acts=billActs();$('event-card').className='event-card';$('event-card').innerHTML=`<div class="poster"><div class="poster-top"><small>ONE FIELD · FOUR STAGES · QUESTIONABLE TOILETS</small><div class="mega">MEGA</div><div class="festival">FESTIVAL</div></div><div class="poster-meta">SATURDAY · GATES 11:00 · NO REFUNDS · RAIN OR WORSE</div><div class="bill">${acts.map((a,i)=>`<span class="act ${tierFor(i)} ${a===state.name?'player':''} ${i>12?'dot':''}">${a}</span>`).join('')}</div><div class="poster-foot"><span>${message||`#${state.rank} · ${tierName(state.rank)} · ${TOTAL_WEEKS-state.week+1} WEEKS TO MEGA`}</span><button id="plan" class="poster-button">PLAN THIS WEEK →</button></div></div>`;$('plan').onclick=showOpportunities;save()}
function drawOffers(){const pool=[...opportunities].sort(()=>Math.random()-.5),left=TOTAL_WEEKS-state.week+1,picked=[];for(const o of pool){if(picked.length===3)break;if(o.cost<=state.cash&&o.weeks<=left)picked.push(o)}state.offerIds=picked.map(o=>o.id);return picked}
function currentOffers(){return state.offerIds.map(id=>opportunities.find(o=>o.id===id)).filter(Boolean)}
function showOpportunities(){let offers=currentOffers();if(!offers.length)offers=drawOffers();$('event-card').className='event-card';$('event-card').innerHTML=`<div class="opportunity-screen"><div class="event-label">${TOTAL_WEEKS-state.week+1} WEEKS TO MEGA</div><div class="event-title">WHAT DO WE DO THIS WEEK?</div><div class="opportunity-list">${offers.map(o=>`<button class="opportunity" data-id="${o.id}"><strong>${o.title}</strong><small>${o.meta}</small><span>${o.copy}</span></button>`).join('')}</div><button id="pass" class="pass-button">PASS · LOSE A WEEK →</button></div>`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>chooseOpportunity(b.dataset.id));$('pass').onclick=()=>{state.week++;state.chaos=Math.max(0,state.chaos-2);state.offerIds=[];showPoster('YOU PASSED. THOSE OFFERS ARE GONE.')}}
function chooseOpportunity(id){const o=opportunities.find(x=>x.id===id);if(!o||o.cost>state.cash)return;state.cash-=o.cost;state.offerIds=[];state.active={...o};renderStats();const p=o.problem;$('event-card').className='event-card';$('event-card').innerHTML=`<div class="crisis"><div class="event-label">${o.title}</div><div class="event-title">${p[0]}</div><p class="event-copy">${p[1]}</p><div class="choices"><button class="choice" data-fix="0">${p[2]}</button><button class="choice" data-fix="1">${p[3]}</button></div></div>`;document.querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>resolveOpportunity(+b.dataset.fix))}
function resolveOpportunity(choice){const a=state.active,oldRank=state.rank;let move=a.base,chaosChange=0,text='';const gamble=choice===0,danger=Math.max(.08,Math.min(.75,.15+state.chaos/120+a.risk/30));if(gamble){if(Math.random()>danger){move+=3+Math.floor(Math.random()*4);chaosChange=3+Math.max(0,a.risk);text='Against all available evidence, this works brilliantly.'}else{move=-(2+Math.floor(Math.random()*5));chaosChange=5+Math.max(0,a.risk);text='This becomes the part everyone remembers for the wrong reason.'}}else{move=Math.max(0,move-2);chaosChange=Math.min(2,a.risk);text='Not glamorous. It works.'}
if(a.id==='rehearse'){chaosChange=gamble?2:-7;move=gamble?2:1;text=gamble?'Lou gets his solo. It is extremely long.':'For one week, the band behaves like adults.'}
if(a.id==='tour'&&choice===0){if(state.cash>=20){state.cash-=20;move+=2;text='£20 later, the van moves. So does the band.'}else{move=-5;chaosChange+=5;text='You cannot afford the tow. Leeds keeps you.'}}
if(a.id==='tour'&&choice===1){const rel=state.relations.dentists||0;if(rel>0){move+=5;chaosChange=-2;text='The Dentists remember you helped them. Their van arrives exactly on time.'}else{move=-4;chaosChange+=4;text='The Dentists remember everything. Especially the boring comment.'}}
if(a.relation)state.relations[a.relation]=(state.relations[a.relation]||0)+(gamble?1:0);state.rank-=move;state.chaos+=chaosChange;state.week+=a.weeks;state.active=null;clamp();renderStats();const actual=oldRank-state.rank;$('event-card').className='event-card';$('event-card').innerHTML=`<div class="crisis aftermath"><div class="event-label">${a.title}</div><div class="event-title">${text}</div><div class="result-line">${actual>0?'↑ '+oldRank+' → #'+state.rank:actual<0?'↓ '+oldRank+' → #'+state.rank:'BILLING UNCHANGED'}${chaosChange?` · CHAOS ${chaosChange>0?'+':''}${chaosChange}`:''}</div><button id="bill" class="big-button">SEE THE UPDATED BILL →</button></div>`;$('bill').onclick=()=>showPoster(actual>0?`${state.name} MOVES UP THE BILL`:actual<0?`${state.name} DROPS DOWN THE BILL`:'THE BILL IS UNCHANGED');save()}
function showEnd(win,title,copy){renderStats();$('event-card').className='event-card';$('event-card').innerHTML=`<div class="crisis ${win?'win':'lose'}"><div class="event-label">MEGA FESTIVAL</div><div class="event-title">${title}</div><p class="event-copy">${copy}</p><div class="result-line">FINAL BILLING: #${state.rank}</div><button id="again" class="big-button">START ANOTHER BAND →</button></div>`;$('again').onclick=reset}
function render(){$('masthead').classList.add('hidden');$('setup').classList.add('hidden');$('game').classList.remove('hidden');showPoster('FIND YOUR BAND. YES, THAT TINY ONE.')}
function start(){state=newState($('band-name').value.trim());save();render()}
function reset(){Object.keys(localStorage).filter(k=>k.startsWith('headlinerSave')||k.startsWith('bandManagerSave')).forEach(k=>localStorage.removeItem(k));location.reload()}
$('start-btn').onclick=start;$('reset-btn').onclick=reset;$('band-name').addEventListener('keydown',e=>{if(e.key==='Enter')start()});
const saved=localStorage.getItem('headlinerSaveV2');if(saved){try{state=JSON.parse(saved);render()}catch(e){localStorage.removeItem('headlinerSaveV2')}}