const $=id=>document.getElementById(id);
const bassNames=['Dave','Steve','Colin','Gary','Trevor','Nigel','Kev','Martin','Other Dave','Pete','Alan'];
const venues=[['Dog & Duck',45],['Wheezing Ferret',95],['Electric Ballroom',180],['Majestic',500]];
const festival=['THE MEGA FESTIVAL',50000];
const MAX_WEEKS=20;
let state;
const situations={rehearse:[
{who:'lou',icon:'🎸',title:'LOU WANTS A LONGER SOLO.',copy:'Jane says the song is three minutes. Lou says exactly.',choices:[['LET HIM HAVE IT',{lou:-2,jane:1,chaos:4,ready:1},'Lou plays for eleven minutes. Jane remembers this.','louSolo'],['BACK JANE',{lou:2,jane:-1,rep:2,ready:1},'Lou says “fine.” It is not fine.','louCut']]},
{who:'jane',icon:'🎤',title:'JANE CHANGED THE KEY.',copy:'Nobody can play it now. Jane says it “feels better.”',choices:[['CHANGE IT BACK',{jane:2,chaos:2,ready:1},'Jane sings the old key sarcastically.','janeKey'],['LEARN THE NEW KEY',{jane:-2,lou:1,ready:2},'Jane is delighted. Lou preferred the old key.','newKey']]},
{who:'mick',icon:'🥁',title:'MICK WROTE A SONG.',copy:'Everyone has stopped rehearsing and is looking at you.',choices:[['HEAR IT',{mick:-2,rep:2,ready:1},'It is annoyingly good.','mickSong'],['NOT TODAY',{mick:2,chaos:4,ready:2},'You finish rehearsal. Mick remembers this.','mickRejected']]},
{who:'lou',icon:'🎼',title:'THE BASS PART IS WRONG.',copy:'Lou says the bassist misses the change. The bassist says there is no change.',choices:[['BACK LOU',{lou:-1,chaos:2,ready:2},'There was a change. Nobody told the bassist.','bassFight'],['BACK THE BASSIST',{lou:2,chaos:5,ready:1},'There was a change. Awkward.','louBass']]}
],promote:[
{who:'jane',icon:'📄',title:'THE FLYERS ARE READY.',copy:'Lou’s photo is bigger. He says it happened automatically.',choices:[['PRINT THEM',{lou:-1,jane:2,buzz:2,chaos:2},'Jane has found a ruler.','bigLou'],['MAKE LOU SMALLER',{lou:2,jane:-1,buzz:1,rep:2},'Lou has also found a ruler.','smallLou']]},
{who:'mick',icon:'🌐',title:'MICK BOUGHT THE DOMAIN.',copy:'It is long, misspelled and already on 200 stickers.',choices:[['USE IT',{mick:-2,buzz:2,chaos:4},'Nobody can type it. Mick is thrilled.','mickDomain'],['BUY A NORMAL ONE · £12',{cash:-12,mick:2,buzz:1,rep:3},'Mick peels a sticker off his drum.','domainTaken']]},
{who:'jane',icon:'📸',title:'BAND PHOTO DAY.',copy:'Nobody agrees where to stand. Mick is wearing shorts.',choices:[['TAKE THE PHOTO',{buzz:2,rep:2,chaos:2},'It is somehow your best photo.','shortsPhoto'],['SEND MICK HOME',{mick:2,jane:-1,buzz:1,rep:3},'It looks serious. Mick is wounded.','mickPhoto']]},
{who:'lou',icon:'☠️',title:'THE LOGO MEETING.',copy:'Jane wants minimal. Lou drew a skull. Mick drew a worse skull.',choices:[['USE JANE’S',{jane:-2,lou:1,mick:1,buzz:1,rep:3},'Elegant. Two people hate it.','janeLogo'],['USE THE WORSE SKULL',{mick:-2,jane:1,buzz:2,chaos:5},'People inexplicably love it.','skullLogo']]}
]};
const sceneEvents=[
{band:'THE STATIC KITTENS',title:'THE STATIC KITTENS NEED A SUPPORT BAND.',copy:'Their opener dropped out. Tonight.',choices:[['DO IT',{fans:12,rep:3,chaos:5,static:1},'You are under-rehearsed. The crowd loves you anyway.'],['SAVE YOURSELVES',{ready:1,static:-1},'Jane calls this professional. Mick calls it cowardice.']]},
{band:'THE STATIC KITTENS',title:'THE STATIC KITTENS ARE HAVING A PARTY.',copy:'Your next gig is getting close. Mick is already there.',choices:[['GO GET MICK',{mick:1,chaos:-3},'Mick calls you his mum. He comes home.'],['GO TO THE PARTY',{buzz:1,chaos:8,static:1},'Terrible preparation. Excellent networking.']]},
{band:'THE DENTISTS',title:'THE DENTISTS GOT A BETTER SLOT.',copy:'They are irritatingly professional. They also own matching flight cases.',choices:[['CONGRATULATE THEM',{rep:2,dentists:1},'Jane says it through her teeth.'],['CALL THEM BORING',{buzz:2,chaos:4,dentists:-1},'The quote appears in the local paper.']]},
{band:'VELVET KNIFE',title:'VELVET KNIFE WANT TO SHARE A VAN.',copy:'Their van smells strange. Their guitarist knows everyone.',choices:[['PILE IN',{buzz:2,chaos:7,velvet:1},'You meet three promoters and lose one shoe.'],['TAKE THE TRAIN',{cash:-15,chaos:-2},'Nobody has fun. Everybody arrives.']]},
{band:'THE STATIC KITTENS',title:'THE STATIC KITTENS OWE YOU ONE.',copy:'Their manager knows someone on the Mega Festival booking team.',requires:'static',choices:[['CALL IN THE FAVOUR',{rep:5,buzz:1},'For the first time, the festival booker knows your name.'],['SAVE THE FAVOUR',{static:1},'Jane says this had better be worth it.']]}
];
const chaosEvents=[
{title:'YOUR BASSIST HAS QUIT.',copy:'Nobody is entirely sure why. Unfortunately, he owned the van.',choices:[['FIND ANOTHER BASSIST',{cash:-10,chaos:3},'You find one. He says his name is Gary.'],['ASK THE STATIC KITTENS',{static:-1,chaos:-2},'They lend you Pete. Pete is alarmingly competent.']]},
{title:'MICK HAS DISAPPEARED.',copy:'Rehearsal started two hours ago. His girlfriend says he is “thinking.”',choices:[['GO FIND HIM',{ready:-1,chaos:-4},'You find him in a café. He has written another song.'],['REHEARSE WITHOUT HIM',{mick:2,ready:1,chaos:3},'Lou says it was your best rehearsal.']]},
{title:'JANE SAYS IT IS HER OR LOU.',copy:'Lou says that is absolutely fine with him.',choices:[['LOCK THEM IN A ROOM',{chaos:-6,rep:-1},'Forty minutes later they have written a song together.'],['CANCEL REHEARSAL',{ready:-1,chaos:2},'Nobody leaves the band. Yet.']]},
{title:'SOMEONE SPENT THE BAND MONEY.',copy:'There is now a smoke machine. Nobody will admit buying it.',choices:[['KEEP IT',{cash:-25,buzz:2,chaos:5},'It is objectively excellent.'],['RETURN IT',{chaos:-3,mick:1},'Mick looks personally betrayed.']]}
];
function newState(name){return{name:name.toUpperCase()||'SUPERMODEL',week:1,cash:120,fans:18,rep:2,chaos:12,bass:'Dave',moods:{jane:0,lou:0,mick:0},grudges:{jane:'',lou:'',mick:''},ready:0,buzz:0,prepWeeks:3,venueIndex:0,lastSituation:'',gigResult:null,relations:{static:0,dentists:0,velvet:0},qualified:false,pendingScene:false};}
function save(){localStorage.setItem('bandManagerSaveV6',JSON.stringify(state));}function random(a){return a[Math.floor(Math.random()*a.length)];}function clamp(){['cash','fans','rep','chaos'].forEach(k=>state[k]=Math.max(0,state[k]));state.ready=Math.max(0,Math.min(3,state.ready));state.buzz=Math.max(0,Math.min(3,state.buzz));Object.keys(state.moods).forEach(k=>state.moods[k]=Math.max(0,Math.min(2,state.moods[k])));}
function apply(e){Object.entries(e).forEach(([k,v])=>{if(['jane','lou','mick'].includes(k))state.moods[k]+=v;else if(['static','dentists','velvet'].includes(k))state.relations[k]+=v;else state[k]=(state[k]||0)+v});clamp();}function visible(e){return Object.entries(e).filter(([k])=>['cash','fans','rep','chaos','ready','buzz'].includes(k)).map(([k,v])=>`${v>0?'+':''}${v} ${k==='cash'?'£ CASH':k.toUpperCase()}`).join(' · ');}function bar(n){return `<span class="bar">${'<i></i>'.repeat(n)}${'<em></em>'.repeat(3-n)}</span>`;}function readiness(){return ['NOT READY','SHAKY','GOOD','TIGHT'][state.ready];}function currentVenue(){return state.qualified?festival:venues[state.venueIndex];}function crowdEstimate(){const v=currentVenue();return Math.min(v[1],Math.max(5,Math.round(state.buzz*18+state.fans*.35+7)));}function weeksLeft(){return Math.max(0,MAX_WEEKS-state.week+1);}function bandState(){const a=Object.values(state.moods).filter(x=>x>=2).length;return a>=2?'BARELY SPEAKING':a===1?'TENSE':'SURPRISINGLY CIVIL';}
function renderStats(){$('band-title').textContent=state.name;$('week').textContent=state.week;$('cash').textContent=state.cash;$('fans').textContent=state.fans;$('rep').textContent=state.rep;$('chaos').textContent=state.chaos;$('roster').innerHTML='';}
function festivalStatus(){return state.qualified?'★ YOU’RE ON THE BILL':state.venueIndex>=3?'👀 BOOKER IS WATCHING':'✕ NOT ON THE BILL';}
function checkFailure(){if(state.week>MAX_WEEKS&&!state.qualified){showLose('THE FESTIVAL BILL IS FULL.','You ran out of time. The Dentists got a slot.');return true;}if(state.chaos>=60){showLose('THE BAND HAS SPLIT UP.','Nobody agrees who quit first. The Mega Festival will have to wait.');return true;}return false;}
function showHome(){renderStats();if(checkFailure())return;const v=currentVenue();if(state.qualified)return showFestivalPrep();$('event-card').className='paper event-card home-card';$('event-card').innerHTML=`<div class="festival-banner"><small>THE GOAL</small><strong>GET TO THE MEGA FESTIVAL</strong><span>${weeksLeft()} WEEKS · ${festivalStatus()}</span></div><div class="gig-kicker">NEXT STEP ON THE CIRCUIT</div><div class="venue-name">${v[0]}</div><div class="venue-cap">CAPACITY ${v[1]}</div><div class="weeks-left">${state.prepWeeks} WEEK${state.prepWeeks===1?'':'S'} TO GIG NIGHT</div><div class="prep-goals"><div><small>CAN WE PLAY THE SET?</small><strong>${bar(state.ready)} ${readiness()}</strong></div><div><small>WILL ANYONE COME?</small><strong>${bar(state.buzz)} ${crowdEstimate()} EXPECTED</strong></div></div><div class="event-title action-title">THIS WEEK</div><div class="action-grid"><button class="choice action" data-action="rehearse"><b>🎸 REHEARSE</b><small>Sound better.</small></button><button class="choice action" data-action="promote"><b>📄 PROMOTE</b><small>Fill the room.</small></button></div>`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>chooseAction(b.dataset.action));save();}
function showFestivalPrep(){if(state.prepWeeks<=0)return showGigNight();$('event-card').className='paper event-card home-card festival-prep';$('event-card').innerHTML=`<div class="festival-banner qualified"><small>THE MEGA FESTIVAL</small><strong>YOU’RE ON THE BILL.</strong><span>STAGE FOUR · 14:20</span></div><div class="weeks-left">${state.prepWeeks} WEEK${state.prepWeeks===1?'':'S'} TO THE BIGGEST GIG OF YOUR LIFE</div><div class="prep-goals"><div><small>SET</small><strong>${bar(state.ready)} ${readiness()}</strong></div><div><small>BAND</small><strong>${bandState()}</strong></div></div><div class="event-title action-title">THIS WEEK</div><div class="action-grid"><button class="choice action" data-action="rehearse"><b>🎸 REHEARSE</b></button><button class="choice action" data-action="promote"><b>📄 MAKE NOISE</b></button></div>`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>chooseAction(b.dataset.action));save();}
function chooseAction(a){const pool=situations[a],available=pool.filter(s=>s.title!==state.lastSituation),s=random(available.length?available:pool);state.lastSituation=s.title;showSituation(s,a);}function showSituation(s,a){$('event-card').className='paper event-card';$('event-card').innerHTML=`<div class="event-label">${a==='rehearse'?'REHEARSAL':'PROMOTION'} · ${state.prepWeeks} WEEK${state.prepWeeks===1?'':'S'} TO GO</div><div class="event-icon">${s.icon}</div><div class="event-title">${s.title}</div><p class="event-copy">${s.copy}</p><div class="choices">${s.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${c[0]}</button>`).join('')}</div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveSituation(s,+b.dataset.choice));}function resolveSituation(s,i){const c=s.choices[i];apply(c[1]);$('event-card').innerHTML=`<div class="event-label">ONE WEEK CLOSER</div><div class="event-title">${c[2]}</div><div class="result"><strong>${visible(c[1])}</strong></div><button id="next" class="big-button continue">${state.prepWeeks===1?'GIG NIGHT →':'NEXT WEEK →'}</button>`;$('next').onclick=finishPrepWeek;save();}
function finishPrepWeek(){state.week++;state.prepWeeks--;if(checkFailure())return;if(state.prepWeeks<=0)return showGigNight();if(state.chaos>=28&&Math.random()<.38)return showChaosEvent();if(Math.random()<.22)return showSceneEvent();showHome();}
function showSceneEvent(){let pool=sceneEvents.filter(e=>!e.requires||state.relations[e.requires]>0);const e=random(pool);showExternalEvent(e,e.band);}function showChaosEvent(){showExternalEvent(random(chaosEvents),'BAND CHAOS');}
function showExternalEvent(e,label){$('event-card').className='paper event-card scene-card';$('event-card').innerHTML=`<div class="event-label">${label}</div><div class="event-title">${e.title}</div><p class="event-copy">${e.copy}</p><div class="choices">${e.choices.map((c,i)=>`<button class="choice" data-ext="${i}">${c[0]}</button>`).join('')}</div>`;document.querySelectorAll('[data-ext]').forEach(b=>b.onclick=()=>{const c=e.choices[+b.dataset.ext];apply(c[1]);if(e.title.includes('BASSIST'))state.bass=random(bassNames.filter(n=>n!==state.bass));$('event-card').innerHTML=`<div class="event-label">AFTERMATH</div><div class="event-title">${c[2]}</div><div class="result"><strong>${visible(c[1])}</strong></div><button id="ext-next" class="big-button continue">BACK TO WORK →</button>`;$('ext-next').onclick=showHome;save();});}
function showGigNight(){const v=currentVenue();$('event-card').className='paper event-card gig-night';$('event-card').innerHTML=`<div class="tonight">${state.qualified?'FESTIVAL DAY.':'TONIGHT.'}</div><div class="venue-name">${v[0]}</div><div class="venue-cap">${state.qualified?'STAGE FOUR · 14:20':'CAPACITY '+v[1]}</div><div class="night-check"><div><small>EXPECTED</small><strong>${state.qualified?'THOUSANDS':crowdEstimate()+' / '+v[1]}</strong></div><div><small>SET</small><strong>${readiness()}</strong></div><div><small>BAND</small><strong>${bandState()}</strong></div></div><button id="play" class="big-button play-button">${state.qualified?'PLAY THE MEGA FESTIVAL →':'PLAY THE GIG →'}</button>`;$('play').onclick=calculateGig;}
function calculateGig(){const v=currentVenue(),cap=v[1],anger=Object.values(state.moods).filter(x=>x>=2).length;let quality=state.ready*18+state.rep*2-Math.max(0,state.chaos-20)/3+Math.random()*18,demand=state.buzz*18+state.fans*.35+Math.random()*15,turnout=state.qualified?Math.min(9000,Math.max(800,Math.round(1200+state.fans*8+state.buzz*700+Math.random()*1800))):Math.max(5,Math.min(cap,Math.round(demand))),story;if(state.ready===0)story='YOU WERE NOT READY.';else if(anger>=2&&quality>45){story='EVERYONE IS FURIOUS. THE GIG IS INCREDIBLE.';quality+=12;}else if(state.moods.mick>=2&&Math.random()<.45){story='MICK MISSES THE FIRST SONG.';quality-=12;}else if(state.moods.jane>=2&&Math.random()<.4)story='JANE CHANGES THE SET LIST ON STAGE.';else if(state.moods.lou>=2&&Math.random()<.4)story='LOU TAKES THE SOLO ANYWAY.';else story=quality>55?'THE BAND ACTUALLY SOUNDS GOOD.':'YOU GET THROUGH IT.';if(state.buzz===0&&!state.qualified)turnout=Math.min(turnout,8);let performance=Math.max(.15,Math.min(1.2,quality/65)),newFans=Math.max(0,Math.round(turnout*(state.qualified?.08:.25)*performance)),money=state.qualified?250:Math.round(turnout*.7)-18;if(state.ready===0){newFans=Math.floor(newFans*.25);money-=12;}const success=state.qualified?quality>=45:turnout>=cap*.60&&quality>=35;state.gigResult={venue:v[0],cap,turnout,story,newFans,money,success,quality,festival:state.qualified};showGigReveal(0);}
function showGigReveal(step){const g=state.gigResult;if(step===0){$('event-card').className='paper event-card';$('event-card').innerHTML=`<div class="reveal-number">${g.turnout.toLocaleString()}</div><div class="event-title">PEOPLE CAME.</div><button id="reveal" class="big-button continue">AND THEN →</button>`;$('reveal').onclick=()=>showGigReveal(1);return;}if(step===1){$('event-card').innerHTML=`<div class="event-label">ON STAGE</div><div class="event-title">${g.story}</div><button id="reveal" class="big-button continue">WHAT HAPPENED? →</button>`;$('reveal').onclick=()=>showGigReveal(2);return;}state.cash+=g.money;state.fans+=g.newFans;state.rep+=g.quality>55?4:g.quality<25?-2:1;clamp();if(g.festival)return g.success?showWin():showLose('YOU MADE IT. YOU BLEW IT.','The Mega Festival happened. So did Mick. At least you got there.');if(g.success){state.venueIndex++;if(state.venueIndex>=venues.length){state.qualified=true;state.prepWeeks=3;}}renderStats();$('event-card').innerHTML=`<div class="event-label">GIG OVER</div><div class="event-title">${g.success?(state.qualified?'THE FESTIVAL BOOKER WANTS YOU.':'THE PROMOTER NOTICED.'):'NOT YOUR NIGHT.'}</div><div class="result big-result"><strong>${g.money>=0?'+':''}£${g.money} · +${g.newFans} FANS</strong></div><button id="after" class="big-button continue">${state.qualified?'WE’RE ON THE BILL →':g.success?'NEXT VENUE →':'TRY AGAIN →'}</button>`;$('after').onclick=afterGig;save();}
function afterGig(){state.ready=0;state.buzz=0;state.prepWeeks=3;state.gigResult=null;Object.keys(state.moods).forEach(k=>state.moods[k]=Math.max(0,state.moods[k]-1));state.week++;if(checkFailure())return;if(!state.qualified&&Math.random()<.45)return showSceneEvent();showHome();}
function showWin(){$('event-card').className='paper event-card win';$('event-card').innerHTML=`<div class="event-label">THE MEGA FESTIVAL</div><div class="event-title">YOU ACTUALLY DID IT.</div><p class="event-copy">From the Dog & Duck to Stage Four.<br><br>The band is still together. Technically.</p><button id="again-btn" class="big-button">START ANOTHER BAND</button>`;$('again-btn').onclick=reset;}
function showLose(title,copy){$('event-card').className='paper event-card lose';$('event-card').innerHTML=`<div class="event-label">GAME OVER</div><div class="event-title">${title}</div><p class="event-copy">${copy}</p><button id="again-btn" class="big-button">START ANOTHER BAND</button>`;$('again-btn').onclick=reset;}
function render(){$('masthead').classList.add('hidden');$('setup').classList.add('hidden');$('game').classList.remove('hidden');showHome();}function start(){state=newState($('band-name').value.trim());save();render();}function reset(){['bandManagerSave','bandManagerSaveV2','bandManagerSaveV3','bandManagerSaveV4','bandManagerSaveV5','bandManagerSaveV6'].forEach(k=>localStorage.removeItem(k));location.reload();}$('start-btn').onclick=start;$('reset-btn').onclick=reset;$('band-name').addEventListener('keydown',e=>{if(e.key==='Enter')start();});const saved=localStorage.getItem('bandManagerSaveV6');if(saved){try{state=JSON.parse(saved);render()}catch(e){localStorage.removeItem('bandManagerSaveV6')}}