const $=id=>document.getElementById(id);
const bassNames=['Dave','Steve','Colin','Gary','Trevor','Nigel','Kev','Martin','Other Dave','Pete','Alan'];
const venues=[['Dog & Duck',45],['Sticky Floor',70],['Wheezing Ferret',95],['Electric Ballroom',180],['Municipal Hall',260],['Majestic',500]];
let state;

const situations={
 rehearse:[
  {who:'lou',icon:'🎸',title:'LOU WANTS A LONGER SOLO.',copy:'Jane says the song is three minutes. Lou says exactly.',choices:[['LET HIM HAVE IT',{lou:-2,jane:1,chaos:3,rep:2},'Lou plays for eleven minutes. Jane remembers this.','louSolo'],['BACK JANE',{lou:2,jane:-1,rep:3},'Lou says “fine.” It is not fine.','louCut']]},
  {who:'jane',icon:'🎤',title:'JANE CHANGED THE KEY.',copy:'Nobody can play it now. Jane says it “feels better.”',choices:[['CHANGE IT BACK',{jane:2,chaos:3},'Jane sings the old key sarcastically.','janeKey'],['LEARN THE NEW KEY',{jane:-2,lou:1,rep:4},'Jane is delighted. Lou says the old key had warmth.','newKey']]},
  {who:'mick',icon:'🥁',title:'MICK WROTE A SONG.',copy:'Everyone has stopped rehearsing and is looking at you.',choices:[['HEAR IT',{mick:-2,rep:3,chaos:2},'It is annoyingly good.','mickSong'],['NOT TODAY',{mick:2,chaos:3},'Mick says he does not care. He absolutely cares.','mickRejected']]},
  {who:'lou',icon:'🎼',title:'THE BASS PART IS WRONG.',copy:'Lou says the bassist misses the change. The bassist says there is no change.',choices:[['BACK LOU',{lou:-1,chaos:3,rep:2},'There was a change. Nobody told the bassist.','bassFight'],['BACK THE BASSIST',{lou:2,chaos:5},'There was a change. There may also be a new bassist.','louBass']]}
 ],
 promote:[
  {who:'jane',icon:'📄',title:'THE FLYERS ARE READY.',copy:'Lou’s photo is bigger. He says it happened automatically.',choices:[['PRINT THEM',{lou:-1,jane:2,fans:12,chaos:3},'Jane has found a ruler.','bigLou'],['MAKE LOU SMALLER',{lou:2,jane:-1,rep:3},'Lou has also found a ruler.','smallLou']]},
  {who:'mick',icon:'🌐',title:'MICK BOUGHT THE DOMAIN.',copy:'It is long, misspelled and already on 200 stickers.',choices:[['USE IT',{mick:-2,fans:7,chaos:4},'Nobody can type it. Mick is thrilled.','mickDomain'],['BUY A NORMAL ONE · £12',{cash:-12,mick:2,rep:4},'Mick quietly peels a sticker off his drum.','domainTaken']]},
  {who:'jane',icon:'📸',title:'BAND PHOTO DAY.',copy:'Nobody agrees where to stand. Mick is wearing shorts.',choices:[['TAKE THE PHOTO',{fans:8,rep:3,chaos:2},'It is somehow your best photo.','shortsPhoto'],['SEND MICK HOME',{mick:2,jane:-1,rep:4},'It looks serious. Mick is wounded.','mickPhoto']]},
  {who:'lou',icon:'☠️',title:'THE LOGO MEETING.',copy:'Jane wants minimal. Lou drew a skull. Mick drew a worse skull.',choices:[['USE JANE’S',{jane:-2,lou:1,mick:1,rep:5},'Elegant. Two people hate it.','janeLogo'],['USE THE WORSE SKULL',{mick:-2,jane:1,fans:10,chaos:5},'People inexplicably love it.','skullLogo']]}
 ]
};

function newState(name){return{name:name.toUpperCase()||'SUPERMODEL',week:1,cash:120,fans:18,rep:2,chaos:12,bass:'Dave',moods:{jane:0,lou:0,mick:0},grudges:{jane:'',lou:'',mick:''},lastAction:'',lastSituation:''};}
function save(){localStorage.setItem('bandManagerSaveV3',JSON.stringify(state));}
function random(a){return a[Math.floor(Math.random()*a.length)];}
function clamp(){['cash','fans','rep','chaos'].forEach(k=>state[k]=Math.max(0,state[k]));Object.keys(state.moods).forEach(k=>state.moods[k]=Math.max(0,Math.min(2,state.moods[k])));}
function moodWord(n){return n>=2?'FURIOUS':n===1?'ANNOYED':'OKAY';}
function grudgeText(who){return state.grudges[who]||({jane:'Watching Lou.',lou:'Has opinions.',mick:'Present, probably.'}[who]);}
function setGrudge(key){const map={louSolo:['jane','Still angry about Lou’s solo.'],louCut:['lou','Still angry about the shortened solo.'],janeKey:['jane','Still angry about the key change.'],newKey:['lou','Still prefers the old key.'],mickSong:['mick','Nobody admitted his song was good.'],mickRejected:['mick','Still remembers you rejected his song.'],bassFight:['lou','Feels vindicated about the bass part.'],louBass:['lou','Still angry about the bass part.'],bigLou:['jane','Still angry about Lou’s giant face.'],smallLou:['lou','Still angry about the flyer.'],mickDomain:['mick','Very proud of his terrible domain.'],domainTaken:['mick','Still angry about the domain.'],shortsPhoto:['jane','Pretending the shorts were intentional.'],mickPhoto:['mick','Still angry about photo day.'],janeLogo:['lou','Still hates Jane’s logo.'],skullLogo:['jane','Still hates the skull.']};if(map[key])state.grudges[map[key][0]]=map[key][1];}
function apply(effects){Object.entries(effects).forEach(([k,v])=>{if(['jane','lou','mick'].includes(k))state.moods[k]+=v;else state[k]=(state[k]||0)+v});clamp();}
function visibleEffects(effects){return Object.entries(effects).filter(([k])=>['cash','fans','rep','chaos'].includes(k)).map(([k,v])=>`${v>0?'+':''}${v} ${k==='cash'?'£ CASH':k.toUpperCase()}`).join(' · ');}

function renderStats(){
 $('band-title').textContent=state.name;$('week').textContent=state.week;$('cash').textContent=state.cash;$('fans').textContent=state.fans;$('rep').textContent=state.rep;$('chaos').textContent=state.chaos;
 $('roster').innerHTML=`<div class="member mood-${state.moods.jane}"><strong>🎤 JANE</strong><small>${moodWord(state.moods.jane)}</small></div><div class="member mood-${state.moods.lou}"><strong>🎸 LOU</strong><small>${moodWord(state.moods.lou)}</small></div><div class="member mood-${state.moods.mick}"><strong>🥁 MICK</strong><small>${moodWord(state.moods.mick)}</small></div><div class="member bassist"><strong>🎸 ${state.bass}</strong><small>BASS · FOR NOW</small></div>`;
}
function showHome(){if(state.fans>=1000)return showWin();renderStats();$('event-card').className='paper event-card home-card';$('event-card').innerHTML=`<div class="event-label">YOUR PROBLEM THIS WEEK</div><div class="feelings"><div><strong>JANE · ${moodWord(state.moods.jane)}</strong><span>${grudgeText('jane')}</span></div><div><strong>LOU · ${moodWord(state.moods.lou)}</strong><span>${grudgeText('lou')}</span></div><div><strong>MICK · ${moodWord(state.moods.mick)}</strong><span>${grudgeText('mick')}</span></div><div><strong>${state.bass.toUpperCase()} · BASS</strong><span>${state.bass==='Gary'?'Owns a van.':'Still here.'}</span></div></div><div class="event-title action-title">WHAT DO YOU DO?</div><div class="action-grid"><button class="choice action" data-action="rehearse">🎸 REHEARSE</button><button class="choice action" data-action="promote">📄 PROMOTE</button><button class="choice action gig-action" data-action="gig">🎟️ BOOK A GIG</button></div>`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>chooseAction(b.dataset.action));save();}
function chooseAction(action){state.lastAction=action;if(action==='gig')return playGig();const pool=situations[action],available=pool.filter(s=>s.title!==state.lastSituation),s=random(available.length?available:pool);state.lastSituation=s.title;showSituation(s,action);}
function callbackFor(s){const who=s.who;if(state.moods[who]>=2&&state.grudges[who])return `<div class="callback">${who.toUpperCase()}: “And I haven't forgotten about that either.”</div>`;return '';}
function showSituation(s,action){$('event-card').className='paper event-card';$('event-card').innerHTML=`<div class="event-icon">${s.icon}</div><div class="event-label">YOU CHOSE TO ${action.toUpperCase()}</div><div class="event-title">${s.title}</div><p class="event-copy">${s.copy}</p>${callbackFor(s)}<div class="choices">${s.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${c[0]}</button>`).join('')}</div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveSituation(s,+b.dataset.choice));}
function resolveSituation(s,i){const c=s.choices[i];apply(c[1]);setGrudge(c[3]);renderStats();const changes=visibleEffects(c[1]);$('event-card').innerHTML=`<div class="event-label">CONSEQUENCE</div><div class="event-title">${c[2]}</div>${changes?`<div class="result"><strong>${changes}</strong></div>`:''}<button id="next-week" class="big-button continue">NEXT WEEK →</button>`;$('next-week').onclick=advanceWeek;save();}
function advanceWeek(){state.week++;if(Math.random()<.14&&state.week>3){state.bass=random(bassNames.filter(n=>n!==state.bass));}save();showHome();}
function hottest(){return Object.entries(state.moods).sort((a,b)=>b[1]-a[1])[0];}
function playGig(){const venue=venues[Math.min(venues.length-1,Math.floor(state.rep/8))],cap=venue[1],angry=Object.values(state.moods).filter(v=>v>=2).length;let turnout=Math.max(8,Math.min(cap,Math.round(state.fans*(.22+Math.random()*.3)+state.rep*3)));let story='THE BAND PLAYS. NOBODY DIES.';let bonus=0;if(angry>=2&&Math.random()<.55){story='EVERYONE IS FURIOUS. THE GIG IS INCREDIBLE.';bonus=14;state.chaos+=7;}else if(state.moods.mick>=2&&Math.random()<.5){story='MICK ARRIVES DURING THE FIRST SONG.';turnout=Math.max(8,turnout-5);state.chaos+=5;}else if(state.moods.jane>=2&&Math.random()<.5){story='JANE CHANGES THE SET LIST ON STAGE.';bonus=7;state.chaos+=4;}else if(state.moods.lou>=2&&Math.random()<.5){story='LOU TAKES THE SOLO ANYWAY.';bonus=8;state.chaos+=4;}else if(Math.max(...Object.values(state.moods))===0){story='EVERYONE GETS ALONG. THE GIG IS WEIRDLY BORING.';bonus=-2;}const money=Math.max(12,Math.round(turnout*(.45+Math.random()*.35))),newFans=Math.max(3,Math.round(turnout*(.12+Math.random()*.18))+bonus);state.cash+=money;state.fans+=newFans;state.rep+=turnout===cap?4:2;Object.keys(state.moods).forEach(k=>state.moods[k]=Math.max(0,state.moods[k]-1));clamp();renderStats();$('event-card').className='paper event-card';$('event-card').innerHTML=`<div class="event-icon">🎟️</div><div class="event-label">${venue[0].toUpperCase()}</div><div class="event-title">${story}</div><p class="event-copy">${turnout===cap?'SOLD OUT.':`${turnout} people showed up.`}</p><div class="result"><strong>+£${money} · +${newFans} FANS</strong></div><button id="next-week" class="big-button continue">NEXT WEEK →</button>`;$('next-week').onclick=advanceWeek;save();}
function showWin(){$('event-card').className='paper event-card win';$('event-card').innerHTML=`<div class="event-icon">★</div><div class="event-label">GOOD LORD</div><div class="event-title">YOU'RE ACTUALLY A BAND NOW.</div><p class="event-copy">1,000 fans. Nobody permanently left.<br><br>Frankly astonishing.</p><button id="again-btn" class="big-button">DO IT AGAIN</button>`;$('again-btn').onclick=reset;}
function render(){$('masthead').classList.add('hidden');$('setup').classList.add('hidden');$('game').classList.remove('hidden');showHome();}
function start(){state=newState($('band-name').value.trim());save();render();}
function reset(){['bandManagerSave','bandManagerSaveV2','bandManagerSaveV3'].forEach(k=>localStorage.removeItem(k));location.reload();}
$('start-btn').onclick=start;$('reset-btn').onclick=reset;$('band-name').addEventListener('keydown',e=>{if(e.key==='Enter')start();});
const saved=localStorage.getItem('bandManagerSaveV3');if(saved){try{state=JSON.parse(saved);render()}catch(e){localStorage.removeItem('bandManagerSaveV3')}}
